import os
import javalang
from collections import defaultdict

class BehaviorPreserver:
    def __init__(self, data, recommendations):
        self.data = data
        self.recommendations = recommendations  # {class_name: module_id}
        self.cluster_map = defaultdict(list)
        for cls, mod in recommendations.items():
            self.cluster_map[mod].append(cls)

    def check_interfaces(self):
        """Static interface checking (Spoon-like behavior using javalang)"""
        violations = []
        for i, path in enumerate(self.data.file_paths):
            try:
                with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                    tree = javalang.parse.parse(f.read())
                caller_mod = self.recommendations[self.data.class_names[i]]
                for _, node in tree.filter(javalang.tree.MethodInvocation):
                    callee = node.member
                    if callee in self.recommendations:
                        callee_mod = self.recommendations[callee]
                        if caller_mod != callee_mod:
                            violations.append(f"Cross-module call: {self.data.class_names[i]} → {callee} ({caller_mod} → {callee_mod})")
            except:
                pass
        return violations

    def generate_test_skeletons(self, output_dir="test_skeletons"):
        """Auto-generate JUnit test skeletons for inter-cluster boundaries"""
        os.makedirs(output_dir, exist_ok=True)
        for mod_id, classes in self.cluster_map.items():
            for cls in classes:
                skeleton = f"""import org.junit.Test;
public class {cls}BoundaryTest {{
    @Test
    public void testInterClusterCalls() {{
        // TODO: Add assertions for calls to other modules
        // Generated by DeepModule BehaviorPreserver
    }}
}}"""
                with open(f"{output_dir}/{cls}BoundaryTest.java", "w") as f:
                    f.write(skeleton)
        print(f"✅ {len(self.cluster_map)*len(next(iter(self.cluster_map.values())))} test skeletons generated in {output_dir}/")

    def differential_symbolic_check(self):
        """Simple differential symbolic execution placeholder (real impl. needs Soot/KLEE)"""
        print("🔍 Running lightweight symbolic boundary check...")
        violations = self.check_interfaces()
        if violations:
            print("⚠️  Potential behavior changes detected:")
            for v in violations[:5]:
                print("   ", v)
            print(f"   ... and {len(violations)-5} more")
        else:
            print("✅ No critical cross-module violations detected.")
        return len(violations) == 0